import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1>My Favorite Quote of the Day</h1>
          <blockquote style={{ color: "pink", fontSize: 20 }}>
            "Faith is taking the first step even when you don't see the whole staircase." — Martin Luther King Jr.

            It's all about trusting the journey, even when the path isn't clear. 🚶‍♂️✨ Keep steady, my friend. You never know where that next step might lead you. 💪 
          </blockquote>
        </main>
        <footer className={styles.footer}>
          <p>Inspirational Quote About Understanding Life's Challenges.</p>
        </footer>
      </div>
    </>
  );
}
